version: 1.1.{build}

environment:
  nodejs_version: "8"
  NETWORK: "mainnet"
  AWS_ACCESS_KEY_ID:
    secure: O0+bBTm/Ud3pxP8nvC3ZuDSkmmlr+b8hVluqpRdJGBg=
  AWS_SECRET_ACCESS_KEY:
    secure: DbpP02aDGoC3Tdsi3+ONm8ov0nuXzEF/Yi453SBKj38qjROzvPXo6qW44bYiKBf4
  CERT_PASS:
    secure: K+PY2zF/5qeJnnKhcCZaqLnVZuAXvuxCXosnzHdtje1C+BMLfAbCJZVt2wTMEyJT
  # Avoid long paths on Windows
  STACK_ROOT: "c:\\sr"

build: off

cache:
  - C:\sr -> installers/daedalus-installer.cabal
  - C:\sr -> installers/stack.yaml

install:
  - ps: Install-Product node $env:nodejs_version x64
  - IF NOT DEFINED APPVEYOR_PULL_REQUEST_NUMBER aws s3 cp --region eu-central-1 s3://iohk-private-2/iohk-windows-certificate-4.p12 C:/iohk-windows-certificate.p12

test_script:
  - scripts\build-installer-win64.bat %APPVEYOR_BUILD_VERSION%

artifacts:
  - path: release\win32-x64\Daedalus-win32-x64
    name: Daedalus Electron application
    type: zip
  - path: installers\daedalus-win64-*-installer.exe
    name: Daedalus Win64 Installer
  - path: node_modules\daedalus-client-api\build-id
    name: cardano-sl-build-id

deploy:
  provider: S3
  access_key_id:
    secure: IEky6PsMzHaKHNBMxR8tQaQI8X7qWRB9+HuEroTVRBk=
  secret_access_key:
    secure: cqjzG96hWB1x3JDbVSbF9E+aJ5jKvIGacJRUDWATHaTOYfSt6Rvive/NrF4lKBIm
  bucket: appveyor-ci-deploy
  region: ap-northeast-1
  folder:
  artifact: Daedalus Win64 Installer
  set_public: true
