version: 0.4.{build}

environment:
  nodejs_version: "6"
  AWS_ACCESS_KEY_ID:
    secure: NoU3qXx0B+48v7PY3RzHrBrSqd4x/3dcJv8WwUzCNyE=
  AWS_SECRET_ACCESS_KEY:
    secure: TIIz2Xtcn63BxDJ9h+2Uj73vJrfmImtlZHh0y2YxGIpwu3eRV9OA+1jhDiG2zPch
  CERT_PASS:
    secure: AvuOn55kobR/QusvSdyyFCCOh5EF/AFNXAUCk9R2brePbiwBwQiscFCX0f/TiupS
  # Avoid long paths on Windows
  STACK_ROOT: "c:\\sr"

build: off

cache:
  - C:\sr -> installers/cardano-installer.cabal
  - C:\sr -> installers/stack.yaml

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install
  - mkdir node_modules\daedalus-client-api
  - cd node_modules\daedalus-client-api
  - ps: Start-FileDownload 'https://ci.appveyor.com/api/projects/jagajaga/cardano-sl/artifacts/CardanoSL.zip?branch=cardano-sl-0.4-rc' -FileName CardanoSL.zip
  - 7z x CardanoSL.zip -y
  - cd ..\..\
  - move node_modules\daedalus-client-api\log-config-prod.yaml installers\log-config-prod.yaml
  - move node_modules\daedalus-client-api\cardano-node.exe installers\
  - move node_modules\daedalus-client-api\cardano-launcher.exe installers\
  - del /f node_modules\daedalus-client-api\*.exe

test_script:
  - SET DAEDALUS_VERSION=%APPVEYOR_BUILD_VERSION%
  # Package frontend
  - npm run package -- --icon installers/icons/64x64
  - cd installers
  # Install stack
  - ps: Start-FileDownload http://www.stackage.org/stack/windows-x86_64 -FileName stack.zip
  - 7z x stack.zip stack.exe
  # Copy DLLs
  # TODO: get rocksdb from rocksdb-haskell
  - mkdir DLLs
  - cd DLLs
  - ps: Start-FileDownload 'https://s3.eu-central-1.amazonaws.com/cardano-sl-testing/DLLs.zip' -FileName DLLs.zip
  - 7z x DLLs.zip
  - del DLLs.zip
  - cd ..
  - IF NOT DEFINED APPVEYOR_PULL_REQUEST_NUMBER aws s3 cp --region eu-central-1 s3://iohk-private/iohk-windows-certificate.p12 C:/iohk-windows-certificate.p12
  - stack setup --no-reinstall
  - appveyor-retry call stack --no-terminal build -j 2 --exec make-installer
  - cd ..

artifacts:
  - path: release\win32-x64\Daedalus-win32-x64
    name: Daedalus Electron application
    type: zip
  - path: installers\daedalus-win64-*-installer.exe
    name: Daedalus Win64 Installer
  - path: node_modules\daedalus-client-api\build-id
    name: cardano-sl-build-id
