status = [
  # Buildkite: osx/linux installers
  "buildkite/daedalus",

  # Appveyor: windows installers
  #"continuous-integration/appveyor/branch",

  # Hydra: we just care about tests attribute set
  "ci/hydra:serokell:daedalus:tests.runFlow",
  "ci/hydra:serokell:daedalus:tests.runLint",
  "ci/hydra:serokell:daedalus:tests.runShellcheck"
]
timeout_sec = 7200
required_approvals = 1
cut_body_after = "## Type of change"
delete_merged_branches = true
block_labels = [ "DO NOT MERGE", "WIP" ]
